/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedConversationsRouteImport } from './routes/_authenticated/conversations'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedHomeIndexRouteImport } from './routes/_authenticated/home/index'
import { Route as AuthenticatedConversationsIndexRouteImport } from './routes/_authenticated/conversations/index'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects/$projectId'
import { Route as AuthenticatedProfileApiKeysRouteImport } from './routes/_authenticated/profile/api-keys'
import { Route as AuthenticatedDeviceCapabilitiesRouteImport } from './routes/_authenticated/device/capabilities'
import { Route as AuthenticatedConversationsConversationIdRouteImport } from './routes/_authenticated/conversations/$conversationId'
import { Route as AuthenticatedProjectsProjectIdIndexRouteImport } from './routes/_authenticated/projects/$projectId/index'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated/admin/users/index'
import { Route as AuthenticatedAdminSettingsIndexRouteImport } from './routes/_authenticated/admin/settings/index'
import { Route as AuthenticatedAdminPluginsIndexRouteImport } from './routes/_authenticated/admin/plugins/index'
import { Route as AuthenticatedAdminOrganizationAccessIndexRouteImport } from './routes/_authenticated/admin/organization-access/index'
import { Route as AuthenticatedAdminGlobalRolesIndexRouteImport } from './routes/_authenticated/admin/global-roles/index'
import { Route as AuthenticatedAdminChangelogIndexRouteImport } from './routes/_authenticated/admin/changelog/index'
import { Route as AuthenticatedAdminAgentsIndexRouteImport } from './routes/_authenticated/admin/agents/index'
import { Route as AuthenticatedProjectsProjectIdConversationsRouteImport } from './routes/_authenticated/projects/$projectId/conversations'
import { Route as AuthenticatedProjectsProjectIdTeamIndexRouteImport } from './routes/_authenticated/projects/$projectId/team/index'
import { Route as AuthenticatedProjectsProjectIdTasksIndexRouteImport } from './routes/_authenticated/projects/$projectId/tasks/index'
import { Route as AuthenticatedProjectsProjectIdSettingsIndexRouteImport } from './routes/_authenticated/projects/$projectId/settings/index'
import { Route as AuthenticatedProjectsProjectIdEnvironmentsIndexRouteImport } from './routes/_authenticated/projects/$projectId/environments/index'
import { Route as AuthenticatedProjectsProjectIdDocsIndexRouteImport } from './routes/_authenticated/projects/$projectId/docs/index'
import { Route as AuthenticatedProjectsProjectIdConversationsIndexRouteImport } from './routes/_authenticated/projects/$projectId/conversations/index'
import { Route as AuthenticatedProjectsProjectIdAutomationIndexRouteImport } from './routes/_authenticated/projects/$projectId/automation/index'
import { Route as AuthenticatedProjectsProjectIdAgentsIndexRouteImport } from './routes/_authenticated/projects/$projectId/agents/index'
import { Route as AuthenticatedAdminAgentsAgentIdIndexRouteImport } from './routes/_authenticated/admin/agents/$agentId/index'
import { Route as AuthenticatedProjectsProjectIdTasksTaskIdRouteImport } from './routes/_authenticated/projects/$projectId/tasks/$taskId'
import { Route as AuthenticatedProjectsProjectIdInteractionsTimelineRouteImport } from './routes/_authenticated/projects/$projectId/interactions/timeline'
import { Route as AuthenticatedProjectsProjectIdInteractionsBacklogRouteImport } from './routes/_authenticated/projects/$projectId/interactions/backlog'
import { Route as AuthenticatedProjectsProjectIdDocsDocIdRouteImport } from './routes/_authenticated/projects/$projectId/docs/$docId'
import { Route as AuthenticatedProjectsProjectIdConversationsConversationIdRouteImport } from './routes/_authenticated/projects/$projectId/conversations/$conversationId'
import { Route as AuthenticatedProjectsProjectIdAutomationAutomationIdRouteImport } from './routes/_authenticated/projects/$projectId/automation/$automationId'
import { Route as AuthenticatedAdminPluginsPluginIdSlugRouteImport } from './routes/_authenticated/admin/plugins/$pluginId/$slug'
import { Route as AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdIndexRouteImport } from './routes/_authenticated/projects/$projectId/environments/$environmentId/index'
import { Route as AuthenticatedProjectsProjectIdAgentsAgentIdIndexRouteImport } from './routes/_authenticated/projects/$projectId/agents/$agentId/index'
import { Route as AuthenticatedProjectsProjectIdPluginsPluginIdSlugRouteImport } from './routes/_authenticated/projects/$projectId/plugins/$pluginId/$slug'
import { Route as AuthenticatedProjectsProjectIdInteractionsSprintsSprintIdRouteImport } from './routes/_authenticated/projects/$projectId/interactions/sprints/$sprintId'
import { Route as AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdTerminalRouteImport } from './routes/_authenticated/projects/$projectId/environments/$environmentId/terminal'
import { Route as AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdConnectRouteImport } from './routes/_authenticated/projects/$projectId/environments/$environmentId/connect'

const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConversationsRoute =
  AuthenticatedConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHomeIndexRoute = AuthenticatedHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConversationsIndexRoute =
  AuthenticatedConversationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConversationsRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileApiKeysRoute =
  AuthenticatedProfileApiKeysRouteImport.update({
    id: '/profile/api-keys',
    path: '/profile/api-keys',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDeviceCapabilitiesRoute =
  AuthenticatedDeviceCapabilitiesRouteImport.update({
    id: '/device/capabilities',
    path: '/device/capabilities',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConversationsConversationIdRoute =
  AuthenticatedConversationsConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedConversationsRoute,
  } as any)
const AuthenticatedProjectsProjectIdIndexRoute =
  AuthenticatedProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/admin/users/',
    path: '/admin/users/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSettingsIndexRoute =
  AuthenticatedAdminSettingsIndexRouteImport.update({
    id: '/admin/settings/',
    path: '/admin/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPluginsIndexRoute =
  AuthenticatedAdminPluginsIndexRouteImport.update({
    id: '/admin/plugins/',
    path: '/admin/plugins/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminOrganizationAccessIndexRoute =
  AuthenticatedAdminOrganizationAccessIndexRouteImport.update({
    id: '/admin/organization-access/',
    path: '/admin/organization-access/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminGlobalRolesIndexRoute =
  AuthenticatedAdminGlobalRolesIndexRouteImport.update({
    id: '/admin/global-roles/',
    path: '/admin/global-roles/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminChangelogIndexRoute =
  AuthenticatedAdminChangelogIndexRouteImport.update({
    id: '/admin/changelog/',
    path: '/admin/changelog/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAgentsIndexRoute =
  AuthenticatedAdminAgentsIndexRouteImport.update({
    id: '/admin/agents/',
    path: '/admin/agents/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdConversationsRoute =
  AuthenticatedProjectsProjectIdConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdTeamIndexRoute =
  AuthenticatedProjectsProjectIdTeamIndexRouteImport.update({
    id: '/team/',
    path: '/team/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdTasksIndexRoute =
  AuthenticatedProjectsProjectIdTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdSettingsIndexRoute =
  AuthenticatedProjectsProjectIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdEnvironmentsIndexRoute =
  AuthenticatedProjectsProjectIdEnvironmentsIndexRouteImport.update({
    id: '/environments/',
    path: '/environments/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdDocsIndexRoute =
  AuthenticatedProjectsProjectIdDocsIndexRouteImport.update({
    id: '/docs/',
    path: '/docs/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdConversationsIndexRoute =
  AuthenticatedProjectsProjectIdConversationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProjectIdConversationsRoute,
  } as any)
const AuthenticatedProjectsProjectIdAutomationIndexRoute =
  AuthenticatedProjectsProjectIdAutomationIndexRouteImport.update({
    id: '/automation/',
    path: '/automation/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdAgentsIndexRoute =
  AuthenticatedProjectsProjectIdAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedAdminAgentsAgentIdIndexRoute =
  AuthenticatedAdminAgentsAgentIdIndexRouteImport.update({
    id: '/admin/agents/$agentId/',
    path: '/admin/agents/$agentId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdTasksTaskIdRoute =
  AuthenticatedProjectsProjectIdTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdInteractionsTimelineRoute =
  AuthenticatedProjectsProjectIdInteractionsTimelineRouteImport.update({
    id: '/interactions/timeline',
    path: '/interactions/timeline',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdInteractionsBacklogRoute =
  AuthenticatedProjectsProjectIdInteractionsBacklogRouteImport.update({
    id: '/interactions/backlog',
    path: '/interactions/backlog',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdDocsDocIdRoute =
  AuthenticatedProjectsProjectIdDocsDocIdRouteImport.update({
    id: '/docs/$docId',
    path: '/docs/$docId',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdConversationsConversationIdRoute =
  AuthenticatedProjectsProjectIdConversationsConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedProjectsProjectIdConversationsRoute,
  } as any)
const AuthenticatedProjectsProjectIdAutomationAutomationIdRoute =
  AuthenticatedProjectsProjectIdAutomationAutomationIdRouteImport.update({
    id: '/automation/$automationId',
    path: '/automation/$automationId',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedAdminPluginsPluginIdSlugRoute =
  AuthenticatedAdminPluginsPluginIdSlugRouteImport.update({
    id: '/admin/plugins/$pluginId/$slug',
    path: '/admin/plugins/$pluginId/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdIndexRoute =
  AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdIndexRouteImport.update(
    {
      id: '/environments/$environmentId/',
      path: '/environments/$environmentId/',
      getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
    } as any,
  )
const AuthenticatedProjectsProjectIdAgentsAgentIdIndexRoute =
  AuthenticatedProjectsProjectIdAgentsAgentIdIndexRouteImport.update({
    id: '/agents/$agentId/',
    path: '/agents/$agentId/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdPluginsPluginIdSlugRoute =
  AuthenticatedProjectsProjectIdPluginsPluginIdSlugRouteImport.update({
    id: '/plugins/$pluginId/$slug',
    path: '/plugins/$pluginId/$slug',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdInteractionsSprintsSprintIdRoute =
  AuthenticatedProjectsProjectIdInteractionsSprintsSprintIdRouteImport.update({
    id: '/interactions/sprints/$sprintId',
    path: '/interactions/sprints/$sprintId',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdTerminalRoute =
  AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdTerminalRouteImport.update(
    {
      id: '/environments/$environmentId/terminal',
      path: '/environments/$environmentId/terminal',
      getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
    } as any,
  )
const AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdConnectRoute =
  AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdConnectRouteImport.update(
    {
      id: '/environments/$environmentId/connect',
      path: '/environments/$environmentId/connect',
      getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/conversations': typeof AuthenticatedConversationsRouteWithChildren
  '/conversations/$conversationId': typeof AuthenticatedConversationsConversationIdRoute
  '/device/capabilities': typeof AuthenticatedDeviceCapabilitiesRoute
  '/profile/api-keys': typeof AuthenticatedProfileApiKeysRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/conversations/': typeof AuthenticatedConversationsIndexRoute
  '/home/': typeof AuthenticatedHomeIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/projects/$projectId/conversations': typeof AuthenticatedProjectsProjectIdConversationsRouteWithChildren
  '/admin/agents/': typeof AuthenticatedAdminAgentsIndexRoute
  '/admin/changelog/': typeof AuthenticatedAdminChangelogIndexRoute
  '/admin/global-roles/': typeof AuthenticatedAdminGlobalRolesIndexRoute
  '/admin/organization-access/': typeof AuthenticatedAdminOrganizationAccessIndexRoute
  '/admin/plugins/': typeof AuthenticatedAdminPluginsIndexRoute
  '/admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
  '/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/admin/plugins/$pluginId/$slug': typeof AuthenticatedAdminPluginsPluginIdSlugRoute
  '/projects/$projectId/automation/$automationId': typeof AuthenticatedProjectsProjectIdAutomationAutomationIdRoute
  '/projects/$projectId/conversations/$conversationId': typeof AuthenticatedProjectsProjectIdConversationsConversationIdRoute
  '/projects/$projectId/docs/$docId': typeof AuthenticatedProjectsProjectIdDocsDocIdRoute
  '/projects/$projectId/interactions/backlog': typeof AuthenticatedProjectsProjectIdInteractionsBacklogRoute
  '/projects/$projectId/interactions/timeline': typeof AuthenticatedProjectsProjectIdInteractionsTimelineRoute
  '/projects/$projectId/tasks/$taskId': typeof AuthenticatedProjectsProjectIdTasksTaskIdRoute
  '/admin/agents/$agentId/': typeof AuthenticatedAdminAgentsAgentIdIndexRoute
  '/projects/$projectId/agents/': typeof AuthenticatedProjectsProjectIdAgentsIndexRoute
  '/projects/$projectId/automation/': typeof AuthenticatedProjectsProjectIdAutomationIndexRoute
  '/projects/$projectId/conversations/': typeof AuthenticatedProjectsProjectIdConversationsIndexRoute
  '/projects/$projectId/docs/': typeof AuthenticatedProjectsProjectIdDocsIndexRoute
  '/projects/$projectId/environments/': typeof AuthenticatedProjectsProjectIdEnvironmentsIndexRoute
  '/projects/$projectId/settings/': typeof AuthenticatedProjectsProjectIdSettingsIndexRoute
  '/projects/$projectId/tasks/': typeof AuthenticatedProjectsProjectIdTasksIndexRoute
  '/projects/$projectId/team/': typeof AuthenticatedProjectsProjectIdTeamIndexRoute
  '/projects/$projectId/environments/$environmentId/connect': typeof AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdConnectRoute
  '/projects/$projectId/environments/$environmentId/terminal': typeof AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdTerminalRoute
  '/projects/$projectId/interactions/sprints/$sprintId': typeof AuthenticatedProjectsProjectIdInteractionsSprintsSprintIdRoute
  '/projects/$projectId/plugins/$pluginId/$slug': typeof AuthenticatedProjectsProjectIdPluginsPluginIdSlugRoute
  '/projects/$projectId/agents/$agentId/': typeof AuthenticatedProjectsProjectIdAgentsAgentIdIndexRoute
  '/projects/$projectId/environments/$environmentId/': typeof AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/conversations/$conversationId': typeof AuthenticatedConversationsConversationIdRoute
  '/device/capabilities': typeof AuthenticatedDeviceCapabilitiesRoute
  '/profile/api-keys': typeof AuthenticatedProfileApiKeysRoute
  '/conversations': typeof AuthenticatedConversationsIndexRoute
  '/home': typeof AuthenticatedHomeIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/admin/agents': typeof AuthenticatedAdminAgentsIndexRoute
  '/admin/changelog': typeof AuthenticatedAdminChangelogIndexRoute
  '/admin/global-roles': typeof AuthenticatedAdminGlobalRolesIndexRoute
  '/admin/organization-access': typeof AuthenticatedAdminOrganizationAccessIndexRoute
  '/admin/plugins': typeof AuthenticatedAdminPluginsIndexRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/admin/plugins/$pluginId/$slug': typeof AuthenticatedAdminPluginsPluginIdSlugRoute
  '/projects/$projectId/automation/$automationId': typeof AuthenticatedProjectsProjectIdAutomationAutomationIdRoute
  '/projects/$projectId/conversations/$conversationId': typeof AuthenticatedProjectsProjectIdConversationsConversationIdRoute
  '/projects/$projectId/docs/$docId': typeof AuthenticatedProjectsProjectIdDocsDocIdRoute
  '/projects/$projectId/interactions/backlog': typeof AuthenticatedProjectsProjectIdInteractionsBacklogRoute
  '/projects/$projectId/interactions/timeline': typeof AuthenticatedProjectsProjectIdInteractionsTimelineRoute
  '/projects/$projectId/tasks/$taskId': typeof AuthenticatedProjectsProjectIdTasksTaskIdRoute
  '/admin/agents/$agentId': typeof AuthenticatedAdminAgentsAgentIdIndexRoute
  '/projects/$projectId/agents': typeof AuthenticatedProjectsProjectIdAgentsIndexRoute
  '/projects/$projectId/automation': typeof AuthenticatedProjectsProjectIdAutomationIndexRoute
  '/projects/$projectId/conversations': typeof AuthenticatedProjectsProjectIdConversationsIndexRoute
  '/projects/$projectId/docs': typeof AuthenticatedProjectsProjectIdDocsIndexRoute
  '/projects/$projectId/environments': typeof AuthenticatedProjectsProjectIdEnvironmentsIndexRoute
  '/projects/$projectId/settings': typeof AuthenticatedProjectsProjectIdSettingsIndexRoute
  '/projects/$projectId/tasks': typeof AuthenticatedProjectsProjectIdTasksIndexRoute
  '/projects/$projectId/team': typeof AuthenticatedProjectsProjectIdTeamIndexRoute
  '/projects/$projectId/environments/$environmentId/connect': typeof AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdConnectRoute
  '/projects/$projectId/environments/$environmentId/terminal': typeof AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdTerminalRoute
  '/projects/$projectId/interactions/sprints/$sprintId': typeof AuthenticatedProjectsProjectIdInteractionsSprintsSprintIdRoute
  '/projects/$projectId/plugins/$pluginId/$slug': typeof AuthenticatedProjectsProjectIdPluginsPluginIdSlugRoute
  '/projects/$projectId/agents/$agentId': typeof AuthenticatedProjectsProjectIdAgentsAgentIdIndexRoute
  '/projects/$projectId/environments/$environmentId': typeof AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/_authenticated/conversations': typeof AuthenticatedConversationsRouteWithChildren
  '/_authenticated/conversations/$conversationId': typeof AuthenticatedConversationsConversationIdRoute
  '/_authenticated/device/capabilities': typeof AuthenticatedDeviceCapabilitiesRoute
  '/_authenticated/profile/api-keys': typeof AuthenticatedProfileApiKeysRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/_authenticated/conversations/': typeof AuthenticatedConversationsIndexRoute
  '/_authenticated/home/': typeof AuthenticatedHomeIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/projects/$projectId/conversations': typeof AuthenticatedProjectsProjectIdConversationsRouteWithChildren
  '/_authenticated/admin/agents/': typeof AuthenticatedAdminAgentsIndexRoute
  '/_authenticated/admin/changelog/': typeof AuthenticatedAdminChangelogIndexRoute
  '/_authenticated/admin/global-roles/': typeof AuthenticatedAdminGlobalRolesIndexRoute
  '/_authenticated/admin/organization-access/': typeof AuthenticatedAdminOrganizationAccessIndexRoute
  '/_authenticated/admin/plugins/': typeof AuthenticatedAdminPluginsIndexRoute
  '/_authenticated/admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/_authenticated/admin/plugins/$pluginId/$slug': typeof AuthenticatedAdminPluginsPluginIdSlugRoute
  '/_authenticated/projects/$projectId/automation/$automationId': typeof AuthenticatedProjectsProjectIdAutomationAutomationIdRoute
  '/_authenticated/projects/$projectId/conversations/$conversationId': typeof AuthenticatedProjectsProjectIdConversationsConversationIdRoute
  '/_authenticated/projects/$projectId/docs/$docId': typeof AuthenticatedProjectsProjectIdDocsDocIdRoute
  '/_authenticated/projects/$projectId/interactions/backlog': typeof AuthenticatedProjectsProjectIdInteractionsBacklogRoute
  '/_authenticated/projects/$projectId/interactions/timeline': typeof AuthenticatedProjectsProjectIdInteractionsTimelineRoute
  '/_authenticated/projects/$projectId/tasks/$taskId': typeof AuthenticatedProjectsProjectIdTasksTaskIdRoute
  '/_authenticated/admin/agents/$agentId/': typeof AuthenticatedAdminAgentsAgentIdIndexRoute
  '/_authenticated/projects/$projectId/agents/': typeof AuthenticatedProjectsProjectIdAgentsIndexRoute
  '/_authenticated/projects/$projectId/automation/': typeof AuthenticatedProjectsProjectIdAutomationIndexRoute
  '/_authenticated/projects/$projectId/conversations/': typeof AuthenticatedProjectsProjectIdConversationsIndexRoute
  '/_authenticated/projects/$projectId/docs/': typeof AuthenticatedProjectsProjectIdDocsIndexRoute
  '/_authenticated/projects/$projectId/environments/': typeof AuthenticatedProjectsProjectIdEnvironmentsIndexRoute
  '/_authenticated/projects/$projectId/settings/': typeof AuthenticatedProjectsProjectIdSettingsIndexRoute
  '/_authenticated/projects/$projectId/tasks/': typeof AuthenticatedProjectsProjectIdTasksIndexRoute
  '/_authenticated/projects/$projectId/team/': typeof AuthenticatedProjectsProjectIdTeamIndexRoute
  '/_authenticated/projects/$projectId/environments/$environmentId/connect': typeof AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdConnectRoute
  '/_authenticated/projects/$projectId/environments/$environmentId/terminal': typeof AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdTerminalRoute
  '/_authenticated/projects/$projectId/interactions/sprints/$sprintId': typeof AuthenticatedProjectsProjectIdInteractionsSprintsSprintIdRoute
  '/_authenticated/projects/$projectId/plugins/$pluginId/$slug': typeof AuthenticatedProjectsProjectIdPluginsPluginIdSlugRoute
  '/_authenticated/projects/$projectId/agents/$agentId/': typeof AuthenticatedProjectsProjectIdAgentsAgentIdIndexRoute
  '/_authenticated/projects/$projectId/environments/$environmentId/': typeof AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/set-password'
    | '/conversations'
    | '/conversations/$conversationId'
    | '/device/capabilities'
    | '/profile/api-keys'
    | '/projects/$projectId'
    | '/conversations/'
    | '/home/'
    | '/profile/'
    | '/projects/$projectId/conversations'
    | '/admin/agents/'
    | '/admin/changelog/'
    | '/admin/global-roles/'
    | '/admin/organization-access/'
    | '/admin/plugins/'
    | '/admin/settings/'
    | '/admin/users/'
    | '/projects/$projectId/'
    | '/admin/plugins/$pluginId/$slug'
    | '/projects/$projectId/automation/$automationId'
    | '/projects/$projectId/conversations/$conversationId'
    | '/projects/$projectId/docs/$docId'
    | '/projects/$projectId/interactions/backlog'
    | '/projects/$projectId/interactions/timeline'
    | '/projects/$projectId/tasks/$taskId'
    | '/admin/agents/$agentId/'
    | '/projects/$projectId/agents/'
    | '/projects/$projectId/automation/'
    | '/projects/$projectId/conversations/'
    | '/projects/$projectId/docs/'
    | '/projects/$projectId/environments/'
    | '/projects/$projectId/settings/'
    | '/projects/$projectId/tasks/'
    | '/projects/$projectId/team/'
    | '/projects/$projectId/environments/$environmentId/connect'
    | '/projects/$projectId/environments/$environmentId/terminal'
    | '/projects/$projectId/interactions/sprints/$sprintId'
    | '/projects/$projectId/plugins/$pluginId/$slug'
    | '/projects/$projectId/agents/$agentId/'
    | '/projects/$projectId/environments/$environmentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/set-password'
    | '/conversations/$conversationId'
    | '/device/capabilities'
    | '/profile/api-keys'
    | '/conversations'
    | '/home'
    | '/profile'
    | '/admin/agents'
    | '/admin/changelog'
    | '/admin/global-roles'
    | '/admin/organization-access'
    | '/admin/plugins'
    | '/admin/settings'
    | '/admin/users'
    | '/projects/$projectId'
    | '/admin/plugins/$pluginId/$slug'
    | '/projects/$projectId/automation/$automationId'
    | '/projects/$projectId/conversations/$conversationId'
    | '/projects/$projectId/docs/$docId'
    | '/projects/$projectId/interactions/backlog'
    | '/projects/$projectId/interactions/timeline'
    | '/projects/$projectId/tasks/$taskId'
    | '/admin/agents/$agentId'
    | '/projects/$projectId/agents'
    | '/projects/$projectId/automation'
    | '/projects/$projectId/conversations'
    | '/projects/$projectId/docs'
    | '/projects/$projectId/environments'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/team'
    | '/projects/$projectId/environments/$environmentId/connect'
    | '/projects/$projectId/environments/$environmentId/terminal'
    | '/projects/$projectId/interactions/sprints/$sprintId'
    | '/projects/$projectId/plugins/$pluginId/$slug'
    | '/projects/$projectId/agents/$agentId'
    | '/projects/$projectId/environments/$environmentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/change-password'
    | '/set-password'
    | '/_authenticated/conversations'
    | '/_authenticated/conversations/$conversationId'
    | '/_authenticated/device/capabilities'
    | '/_authenticated/profile/api-keys'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/conversations/'
    | '/_authenticated/home/'
    | '/_authenticated/profile/'
    | '/_authenticated/projects/$projectId/conversations'
    | '/_authenticated/admin/agents/'
    | '/_authenticated/admin/changelog/'
    | '/_authenticated/admin/global-roles/'
    | '/_authenticated/admin/organization-access/'
    | '/_authenticated/admin/plugins/'
    | '/_authenticated/admin/settings/'
    | '/_authenticated/admin/users/'
    | '/_authenticated/projects/$projectId/'
    | '/_authenticated/admin/plugins/$pluginId/$slug'
    | '/_authenticated/projects/$projectId/automation/$automationId'
    | '/_authenticated/projects/$projectId/conversations/$conversationId'
    | '/_authenticated/projects/$projectId/docs/$docId'
    | '/_authenticated/projects/$projectId/interactions/backlog'
    | '/_authenticated/projects/$projectId/interactions/timeline'
    | '/_authenticated/projects/$projectId/tasks/$taskId'
    | '/_authenticated/admin/agents/$agentId/'
    | '/_authenticated/projects/$projectId/agents/'
    | '/_authenticated/projects/$projectId/automation/'
    | '/_authenticated/projects/$projectId/conversations/'
    | '/_authenticated/projects/$projectId/docs/'
    | '/_authenticated/projects/$projectId/environments/'
    | '/_authenticated/projects/$projectId/settings/'
    | '/_authenticated/projects/$projectId/tasks/'
    | '/_authenticated/projects/$projectId/team/'
    | '/_authenticated/projects/$projectId/environments/$environmentId/connect'
    | '/_authenticated/projects/$projectId/environments/$environmentId/terminal'
    | '/_authenticated/projects/$projectId/interactions/sprints/$sprintId'
    | '/_authenticated/projects/$projectId/plugins/$pluginId/$slug'
    | '/_authenticated/projects/$projectId/agents/$agentId/'
    | '/_authenticated/projects/$projectId/environments/$environmentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  SetPasswordRoute: typeof SetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/conversations': {
      id: '/_authenticated/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AuthenticatedConversationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home/': {
      id: '/_authenticated/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof AuthenticatedHomeIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conversations/': {
      id: '/_authenticated/conversations/'
      path: '/'
      fullPath: '/conversations/'
      preLoaderRoute: typeof AuthenticatedConversationsIndexRouteImport
      parentRoute: typeof AuthenticatedConversationsRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/api-keys': {
      id: '/_authenticated/profile/api-keys'
      path: '/profile/api-keys'
      fullPath: '/profile/api-keys'
      preLoaderRoute: typeof AuthenticatedProfileApiKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/device/capabilities': {
      id: '/_authenticated/device/capabilities'
      path: '/device/capabilities'
      fullPath: '/device/capabilities'
      preLoaderRoute: typeof AuthenticatedDeviceCapabilitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conversations/$conversationId': {
      id: '/_authenticated/conversations/$conversationId'
      path: '/$conversationId'
      fullPath: '/conversations/$conversationId'
      preLoaderRoute: typeof AuthenticatedConversationsConversationIdRouteImport
      parentRoute: typeof AuthenticatedConversationsRoute
    }
    '/_authenticated/projects/$projectId/': {
      id: '/_authenticated/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings/': {
      id: '/_authenticated/admin/settings/'
      path: '/admin/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AuthenticatedAdminSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/plugins/': {
      id: '/_authenticated/admin/plugins/'
      path: '/admin/plugins'
      fullPath: '/admin/plugins/'
      preLoaderRoute: typeof AuthenticatedAdminPluginsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/organization-access/': {
      id: '/_authenticated/admin/organization-access/'
      path: '/admin/organization-access'
      fullPath: '/admin/organization-access/'
      preLoaderRoute: typeof AuthenticatedAdminOrganizationAccessIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/global-roles/': {
      id: '/_authenticated/admin/global-roles/'
      path: '/admin/global-roles'
      fullPath: '/admin/global-roles/'
      preLoaderRoute: typeof AuthenticatedAdminGlobalRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/changelog/': {
      id: '/_authenticated/admin/changelog/'
      path: '/admin/changelog'
      fullPath: '/admin/changelog/'
      preLoaderRoute: typeof AuthenticatedAdminChangelogIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/agents/': {
      id: '/_authenticated/admin/agents/'
      path: '/admin/agents'
      fullPath: '/admin/agents/'
      preLoaderRoute: typeof AuthenticatedAdminAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/conversations': {
      id: '/_authenticated/projects/$projectId/conversations'
      path: '/conversations'
      fullPath: '/projects/$projectId/conversations'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdConversationsRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/team/': {
      id: '/_authenticated/projects/$projectId/team/'
      path: '/team'
      fullPath: '/projects/$projectId/team/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdTeamIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/tasks/': {
      id: '/_authenticated/projects/$projectId/tasks/'
      path: '/tasks'
      fullPath: '/projects/$projectId/tasks/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdTasksIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/settings/': {
      id: '/_authenticated/projects/$projectId/settings/'
      path: '/settings'
      fullPath: '/projects/$projectId/settings/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/environments/': {
      id: '/_authenticated/projects/$projectId/environments/'
      path: '/environments'
      fullPath: '/projects/$projectId/environments/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEnvironmentsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/docs/': {
      id: '/_authenticated/projects/$projectId/docs/'
      path: '/docs'
      fullPath: '/projects/$projectId/docs/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdDocsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/conversations/': {
      id: '/_authenticated/projects/$projectId/conversations/'
      path: '/'
      fullPath: '/projects/$projectId/conversations/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdConversationsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdConversationsRoute
    }
    '/_authenticated/projects/$projectId/automation/': {
      id: '/_authenticated/projects/$projectId/automation/'
      path: '/automation'
      fullPath: '/projects/$projectId/automation/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdAutomationIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/agents/': {
      id: '/_authenticated/projects/$projectId/agents/'
      path: '/agents'
      fullPath: '/projects/$projectId/agents/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/admin/agents/$agentId/': {
      id: '/_authenticated/admin/agents/$agentId/'
      path: '/admin/agents/$agentId'
      fullPath: '/admin/agents/$agentId/'
      preLoaderRoute: typeof AuthenticatedAdminAgentsAgentIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/tasks/$taskId': {
      id: '/_authenticated/projects/$projectId/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/projects/$projectId/tasks/$taskId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdTasksTaskIdRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/interactions/timeline': {
      id: '/_authenticated/projects/$projectId/interactions/timeline'
      path: '/interactions/timeline'
      fullPath: '/projects/$projectId/interactions/timeline'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdInteractionsTimelineRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/interactions/backlog': {
      id: '/_authenticated/projects/$projectId/interactions/backlog'
      path: '/interactions/backlog'
      fullPath: '/projects/$projectId/interactions/backlog'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdInteractionsBacklogRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/docs/$docId': {
      id: '/_authenticated/projects/$projectId/docs/$docId'
      path: '/docs/$docId'
      fullPath: '/projects/$projectId/docs/$docId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdDocsDocIdRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/conversations/$conversationId': {
      id: '/_authenticated/projects/$projectId/conversations/$conversationId'
      path: '/$conversationId'
      fullPath: '/projects/$projectId/conversations/$conversationId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdConversationsConversationIdRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdConversationsRoute
    }
    '/_authenticated/projects/$projectId/automation/$automationId': {
      id: '/_authenticated/projects/$projectId/automation/$automationId'
      path: '/automation/$automationId'
      fullPath: '/projects/$projectId/automation/$automationId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdAutomationAutomationIdRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/admin/plugins/$pluginId/$slug': {
      id: '/_authenticated/admin/plugins/$pluginId/$slug'
      path: '/admin/plugins/$pluginId/$slug'
      fullPath: '/admin/plugins/$pluginId/$slug'
      preLoaderRoute: typeof AuthenticatedAdminPluginsPluginIdSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/environments/$environmentId/': {
      id: '/_authenticated/projects/$projectId/environments/$environmentId/'
      path: '/environments/$environmentId'
      fullPath: '/projects/$projectId/environments/$environmentId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/agents/$agentId/': {
      id: '/_authenticated/projects/$projectId/agents/$agentId/'
      path: '/agents/$agentId'
      fullPath: '/projects/$projectId/agents/$agentId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdAgentsAgentIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/plugins/$pluginId/$slug': {
      id: '/_authenticated/projects/$projectId/plugins/$pluginId/$slug'
      path: '/plugins/$pluginId/$slug'
      fullPath: '/projects/$projectId/plugins/$pluginId/$slug'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPluginsPluginIdSlugRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/interactions/sprints/$sprintId': {
      id: '/_authenticated/projects/$projectId/interactions/sprints/$sprintId'
      path: '/interactions/sprints/$sprintId'
      fullPath: '/projects/$projectId/interactions/sprints/$sprintId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdInteractionsSprintsSprintIdRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/environments/$environmentId/terminal': {
      id: '/_authenticated/projects/$projectId/environments/$environmentId/terminal'
      path: '/environments/$environmentId/terminal'
      fullPath: '/projects/$projectId/environments/$environmentId/terminal'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdTerminalRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/environments/$environmentId/connect': {
      id: '/_authenticated/projects/$projectId/environments/$environmentId/connect'
      path: '/environments/$environmentId/connect'
      fullPath: '/projects/$projectId/environments/$environmentId/connect'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdConnectRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
  }
}

interface AuthenticatedConversationsRouteChildren {
  AuthenticatedConversationsConversationIdRoute: typeof AuthenticatedConversationsConversationIdRoute
  AuthenticatedConversationsIndexRoute: typeof AuthenticatedConversationsIndexRoute
}

const AuthenticatedConversationsRouteChildren: AuthenticatedConversationsRouteChildren =
  {
    AuthenticatedConversationsConversationIdRoute:
      AuthenticatedConversationsConversationIdRoute,
    AuthenticatedConversationsIndexRoute: AuthenticatedConversationsIndexRoute,
  }

const AuthenticatedConversationsRouteWithChildren =
  AuthenticatedConversationsRoute._addFileChildren(
    AuthenticatedConversationsRouteChildren,
  )

interface AuthenticatedProjectsProjectIdConversationsRouteChildren {
  AuthenticatedProjectsProjectIdConversationsConversationIdRoute: typeof AuthenticatedProjectsProjectIdConversationsConversationIdRoute
  AuthenticatedProjectsProjectIdConversationsIndexRoute: typeof AuthenticatedProjectsProjectIdConversationsIndexRoute
}

const AuthenticatedProjectsProjectIdConversationsRouteChildren: AuthenticatedProjectsProjectIdConversationsRouteChildren =
  {
    AuthenticatedProjectsProjectIdConversationsConversationIdRoute:
      AuthenticatedProjectsProjectIdConversationsConversationIdRoute,
    AuthenticatedProjectsProjectIdConversationsIndexRoute:
      AuthenticatedProjectsProjectIdConversationsIndexRoute,
  }

const AuthenticatedProjectsProjectIdConversationsRouteWithChildren =
  AuthenticatedProjectsProjectIdConversationsRoute._addFileChildren(
    AuthenticatedProjectsProjectIdConversationsRouteChildren,
  )

interface AuthenticatedProjectsProjectIdRouteChildren {
  AuthenticatedProjectsProjectIdConversationsRoute: typeof AuthenticatedProjectsProjectIdConversationsRouteWithChildren
  AuthenticatedProjectsProjectIdIndexRoute: typeof AuthenticatedProjectsProjectIdIndexRoute
  AuthenticatedProjectsProjectIdAutomationAutomationIdRoute: typeof AuthenticatedProjectsProjectIdAutomationAutomationIdRoute
  AuthenticatedProjectsProjectIdDocsDocIdRoute: typeof AuthenticatedProjectsProjectIdDocsDocIdRoute
  AuthenticatedProjectsProjectIdInteractionsBacklogRoute: typeof AuthenticatedProjectsProjectIdInteractionsBacklogRoute
  AuthenticatedProjectsProjectIdInteractionsTimelineRoute: typeof AuthenticatedProjectsProjectIdInteractionsTimelineRoute
  AuthenticatedProjectsProjectIdTasksTaskIdRoute: typeof AuthenticatedProjectsProjectIdTasksTaskIdRoute
  AuthenticatedProjectsProjectIdAgentsIndexRoute: typeof AuthenticatedProjectsProjectIdAgentsIndexRoute
  AuthenticatedProjectsProjectIdAutomationIndexRoute: typeof AuthenticatedProjectsProjectIdAutomationIndexRoute
  AuthenticatedProjectsProjectIdDocsIndexRoute: typeof AuthenticatedProjectsProjectIdDocsIndexRoute
  AuthenticatedProjectsProjectIdEnvironmentsIndexRoute: typeof AuthenticatedProjectsProjectIdEnvironmentsIndexRoute
  AuthenticatedProjectsProjectIdSettingsIndexRoute: typeof AuthenticatedProjectsProjectIdSettingsIndexRoute
  AuthenticatedProjectsProjectIdTasksIndexRoute: typeof AuthenticatedProjectsProjectIdTasksIndexRoute
  AuthenticatedProjectsProjectIdTeamIndexRoute: typeof AuthenticatedProjectsProjectIdTeamIndexRoute
  AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdConnectRoute: typeof AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdConnectRoute
  AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdTerminalRoute: typeof AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdTerminalRoute
  AuthenticatedProjectsProjectIdInteractionsSprintsSprintIdRoute: typeof AuthenticatedProjectsProjectIdInteractionsSprintsSprintIdRoute
  AuthenticatedProjectsProjectIdPluginsPluginIdSlugRoute: typeof AuthenticatedProjectsProjectIdPluginsPluginIdSlugRoute
  AuthenticatedProjectsProjectIdAgentsAgentIdIndexRoute: typeof AuthenticatedProjectsProjectIdAgentsAgentIdIndexRoute
  AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdIndexRoute: typeof AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdIndexRoute
}

const AuthenticatedProjectsProjectIdRouteChildren: AuthenticatedProjectsProjectIdRouteChildren =
  {
    AuthenticatedProjectsProjectIdConversationsRoute:
      AuthenticatedProjectsProjectIdConversationsRouteWithChildren,
    AuthenticatedProjectsProjectIdIndexRoute:
      AuthenticatedProjectsProjectIdIndexRoute,
    AuthenticatedProjectsProjectIdAutomationAutomationIdRoute:
      AuthenticatedProjectsProjectIdAutomationAutomationIdRoute,
    AuthenticatedProjectsProjectIdDocsDocIdRoute:
      AuthenticatedProjectsProjectIdDocsDocIdRoute,
    AuthenticatedProjectsProjectIdInteractionsBacklogRoute:
      AuthenticatedProjectsProjectIdInteractionsBacklogRoute,
    AuthenticatedProjectsProjectIdInteractionsTimelineRoute:
      AuthenticatedProjectsProjectIdInteractionsTimelineRoute,
    AuthenticatedProjectsProjectIdTasksTaskIdRoute:
      AuthenticatedProjectsProjectIdTasksTaskIdRoute,
    AuthenticatedProjectsProjectIdAgentsIndexRoute:
      AuthenticatedProjectsProjectIdAgentsIndexRoute,
    AuthenticatedProjectsProjectIdAutomationIndexRoute:
      AuthenticatedProjectsProjectIdAutomationIndexRoute,
    AuthenticatedProjectsProjectIdDocsIndexRoute:
      AuthenticatedProjectsProjectIdDocsIndexRoute,
    AuthenticatedProjectsProjectIdEnvironmentsIndexRoute:
      AuthenticatedProjectsProjectIdEnvironmentsIndexRoute,
    AuthenticatedProjectsProjectIdSettingsIndexRoute:
      AuthenticatedProjectsProjectIdSettingsIndexRoute,
    AuthenticatedProjectsProjectIdTasksIndexRoute:
      AuthenticatedProjectsProjectIdTasksIndexRoute,
    AuthenticatedProjectsProjectIdTeamIndexRoute:
      AuthenticatedProjectsProjectIdTeamIndexRoute,
    AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdConnectRoute:
      AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdConnectRoute,
    AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdTerminalRoute:
      AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdTerminalRoute,
    AuthenticatedProjectsProjectIdInteractionsSprintsSprintIdRoute:
      AuthenticatedProjectsProjectIdInteractionsSprintsSprintIdRoute,
    AuthenticatedProjectsProjectIdPluginsPluginIdSlugRoute:
      AuthenticatedProjectsProjectIdPluginsPluginIdSlugRoute,
    AuthenticatedProjectsProjectIdAgentsAgentIdIndexRoute:
      AuthenticatedProjectsProjectIdAgentsAgentIdIndexRoute,
    AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdIndexRoute:
      AuthenticatedProjectsProjectIdEnvironmentsEnvironmentIdIndexRoute,
  }

const AuthenticatedProjectsProjectIdRouteWithChildren =
  AuthenticatedProjectsProjectIdRoute._addFileChildren(
    AuthenticatedProjectsProjectIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedConversationsRoute: typeof AuthenticatedConversationsRouteWithChildren
  AuthenticatedDeviceCapabilitiesRoute: typeof AuthenticatedDeviceCapabilitiesRoute
  AuthenticatedProfileApiKeysRoute: typeof AuthenticatedProfileApiKeysRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRouteWithChildren
  AuthenticatedHomeIndexRoute: typeof AuthenticatedHomeIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedAdminAgentsIndexRoute: typeof AuthenticatedAdminAgentsIndexRoute
  AuthenticatedAdminChangelogIndexRoute: typeof AuthenticatedAdminChangelogIndexRoute
  AuthenticatedAdminGlobalRolesIndexRoute: typeof AuthenticatedAdminGlobalRolesIndexRoute
  AuthenticatedAdminOrganizationAccessIndexRoute: typeof AuthenticatedAdminOrganizationAccessIndexRoute
  AuthenticatedAdminPluginsIndexRoute: typeof AuthenticatedAdminPluginsIndexRoute
  AuthenticatedAdminSettingsIndexRoute: typeof AuthenticatedAdminSettingsIndexRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
  AuthenticatedAdminPluginsPluginIdSlugRoute: typeof AuthenticatedAdminPluginsPluginIdSlugRoute
  AuthenticatedAdminAgentsAgentIdIndexRoute: typeof AuthenticatedAdminAgentsAgentIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedConversationsRoute: AuthenticatedConversationsRouteWithChildren,
  AuthenticatedDeviceCapabilitiesRoute: AuthenticatedDeviceCapabilitiesRoute,
  AuthenticatedProfileApiKeysRoute: AuthenticatedProfileApiKeysRoute,
  AuthenticatedProjectsProjectIdRoute:
    AuthenticatedProjectsProjectIdRouteWithChildren,
  AuthenticatedHomeIndexRoute: AuthenticatedHomeIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedAdminAgentsIndexRoute: AuthenticatedAdminAgentsIndexRoute,
  AuthenticatedAdminChangelogIndexRoute: AuthenticatedAdminChangelogIndexRoute,
  AuthenticatedAdminGlobalRolesIndexRoute:
    AuthenticatedAdminGlobalRolesIndexRoute,
  AuthenticatedAdminOrganizationAccessIndexRoute:
    AuthenticatedAdminOrganizationAccessIndexRoute,
  AuthenticatedAdminPluginsIndexRoute: AuthenticatedAdminPluginsIndexRoute,
  AuthenticatedAdminSettingsIndexRoute: AuthenticatedAdminSettingsIndexRoute,
  AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
  AuthenticatedAdminPluginsPluginIdSlugRoute:
    AuthenticatedAdminPluginsPluginIdSlugRoute,
  AuthenticatedAdminAgentsAgentIdIndexRoute:
    AuthenticatedAdminAgentsAgentIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  SetPasswordRoute: SetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
