/**
 * Platform bindings are generated by `wrangler types` as the global `Env` interface.
 * Secret bindings are deliberately declared separately because their values never live
 * in wrangler.jsonc. This preserves generated platform types without committing secrets.
 */
type RuntimeConfigBindings = {
  ATTACHMENT_CLEANUP_ENABLED?: string;
  AUTONOMOUS_HOST_ENROLLMENT_SECRET?: string;
  BETTER_AUTH_SECRET?: string;
  BETTER_AUTH_URL?: string;
  ENVIRONMENT?: string;
  INTERNAL_HEALTH_TOKEN?: string;
  TRUSTED_ORIGINS?: string;
};

import type { AgentSession } from "@better-auth/agent-auth";
import type { PermissionGrant } from "./permission/statement";

/**
 * Application-facing bindings intentionally widen Wrangler's generated literal
 * values so unit tests and non-deployed environments can supply their own URLs
 * and environment names. Runtime-only entry points that need Cloudflare's exact
 * generated Env shape should use the global `Env` type directly.
 */
export type AppBindings = Omit<Env, keyof RuntimeConfigBindings> & RuntimeConfigBindings;

export type AppVariables = {
  agentSession: AgentSession;
  permissionActorId: string;
  permissionGrants: PermissionGrant[];
  requestId: string;
};
